version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: docgestor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docgestor-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/docgestor?schema=public"
      JWT_SECRET: "your-secret-key-here"
      PORT: 5000
    depends_on:
      - postgres
    networks:
      - docgestor-network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - docgestor-network

volumes:
  postgres_data:

networks:
  docgestor-network:
    driver: bridge

